
export const SET_WX_JS_URL = 'SET_WX_JS_URL'
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS'
export const UPDATE_DIRECTION = 'UPDATE_DIRECTION'
export const UPDATE_DEVICE = 'UPDATE_DEVICE'
export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_ORDER_LIST = 'SET_ORDER_LIST'
export const SET_ORDER_DETAIL = 'SET_ORDER_DETAIL'
